# Generated by Django 4.0.3 on 2022-03-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='selector_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
