# Generated by Django 4.0.3 on 2022-03-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_rename_pge_url_page_page_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='setted_image',
            new_name='selector_text',
        ),
    ]
