# Generated by Django 4.0.3 on 2022-03-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_rename_setted_image_element_selector_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='screenshot',
            field=models.ImageField(default=str, upload_to=''),
            preserve_default=False,
        ),
    ]
