# Generated by Django 4.0.3 on 2022-03-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_element_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='selector',
            new_name='selector_type',
        ),
    ]
