# Generated by Django 4.0.3 on 2022-03-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_rename_selector_element_selector_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='screenshot',
        ),
    ]
